.\" Manpage for ldms_auth_munge
.\" Contact ovis-help@ca.sandia.gov to correct errors or typos.
.TH man 7 "10 May 2018" "v4" "ldms_auth_munge"


.SH NAME
ldms_auth_munge \- LDMS authentication using munge


.SH SYNOPSIS
.HP
.I ldms_app
.BI "-a munge [-A socket=PATH,compat=1 ]"


.SH DESCRIPTION
\fBldms_auth_munge\fR relies on the \fBmunge\fR service (see \fBmunge\fR(7)) to
authenticate users. The munge daemon (\fBmunged\fR) must be up and running.

The optional \fBsocket\fR option can be used to specify the path to
the munged unix domain socket in the case that munged wasn't using the
default path or there are multiple munge domains configured.

The optional \fBcompat\fR option is used to be backward compatible
with older versions of the auth plugin that sent authentication
messages that assumed that the remote and local IP addresses would be
the same on both sides of the connection. This is not true in many
environments.

.SH SEE ALSO
\fBmunge\fR(7), \fBmunged\fR(8)
