msg_enable
auth_add name=munge
listen xprt=sock port=9012 auth=munge

load name=msg_feedback
# feedback through agg21
config name=msg_feedback auth=munge host=localhost port=9021 xprt=sock cmd_channel=feedback_cmd

prdcr_add name=samp3 host=localhost xprt=sock port=9003 type=active reconnect=1s auth=munge
prdcr_add name=samp4 host=localhost xprt=sock port=9004 type=active reconnect=1s auth=munge
prdcr_subscribe regex=.* message_channel=app
prdcr_subscribe regex=.* message_channel=feedback_cmd
prdcr_start_regex regex=.*
