msg_enable
auth_add name=munge
listen xprt=sock port=9021 auth=munge

prdcr_add name=agg11 host=localhost xprt=sock port=9011 type=active reconnect=1s auth=munge
prdcr_add name=agg12 host=localhost xprt=sock port=9012 type=active reconnect=1s auth=munge
prdcr_subscribe regex=.* message_channel=app
prdcr_start_regex regex=.*
