msg_enable
auth_add name=munge
listen xprt=sock port=9003 auth=munge

load name=msg_feedback
# feedback through agg12
config name=msg_feedback auth=munge host=localhost port=9012 xprt=sock cmd_channel=feedback_cmd
