msg_enable
auth_add name=munge
listen xprt=sock port=9001 auth=munge

load name=msg_feedback
# feedback through agg11
config name=msg_feedback auth=munge host=localhost port=9011 xprt=sock cmd_channel=feedback_cmd
