name: Compatibility test with OVIS-4.3.3

on:
  push:
    branches: [ OVIS-4 ]
  pull_request:
    branches: [ OVIS-4 ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: ovishpc/ovis-4.3.3-centos7
    steps:
    - uses: actions/checkout@v2
    - run: sh autogen.sh
    - name: build and install
      run: ./configure --prefix=/opt/ovis-4 && make && make install
    - name: test preparation
      run: |
        set -e
        mkdir -p /test/logs
        pushd /test/
        ln -s /opt/ovis-4.3.3/sbin/ldmsd ldmsd-4.3.3
        ln -s /opt/ovis-4/sbin/ldmsd ldmsd-4
        cat > ldmsd-4.3.3.sh << EOF
        \#!/bin/bash
        . /opt/ovis-4.3.3/etc/profile.d/set-ovis-variables.sh
        ./ldmsd-4.3.3 $@
        EOF
        chmod 755 ldmsd-4.3.3.sh
        cat > ldmsd-4.sh << EOF
        \#!/bin/bash
        . /opt/ovis-4/etc/profile.d/set-ovis-variables.sh
        ./ldmsd-4 $@
        EOF
        chmod 755 ldmsd-4.sh
        cat > ldms_ls.sh << EOF
        \#!/bin/bash
        . /opt/ovis-4/etc/profile.d/set-ovis-variables.sh
        ldms_ls $@
        EOF
        chmod 755 ldms_ls.sh
        cat > samp-4.3.3.conf << EOF
        load name=meminfo
        config name=meminfo producer=ovis-4.3.3 instance=ovis-4.3.3/meminfo
        start name=meminfo interval=1000000 offset=0
        EOF
        cat > agg-4.3.3.conf << EOF
        prdcr_add name=samp type=active host=localhost port=10000 xprt=sock interval=1000000
        prdcr_start name=samp
        updtr_add name=updtr interval=1000000 offset=200000
        updtr_prdcr_add name=updtr regex=.*
        updtr_start name=updtr
        EOF
        cat > agg-4.conf << EOF
        prdcr_add name=samp type=active host=localhost port=10001 xprt=sock interval=1000000
        prdcr_start name=samp
        updtr_add name=updtr interval=1000000 offset=200000
        updtr_prdcr_add name=updtr regex=.*
        updtr_start name=updtr
        EOF
    - name: compatibility test
      if: ${{ success() }} # all previous steps are good
      run: |
        error() {
                echo "ERROR:" $@
                exit -1
        }
        cd /test
        # samp
        ./ldmsd-4.3.3.sh -c samp-4.3.3.conf -l logs/samp-4.3.3.log -v INFO -x sock:10000
        # agg1
        ./ldmsd-4.3.3.sh -c agg-4.3.3.conf -l logs/agg-4.3.3.log -v INFO -x sock:10001
        sleep 2
        # agg2
        ./ldmsd-4sh -c agg-4.conf -l logs/agg-4.log -v INFO -x sock:10002
        sleep 2
        ./ldms_ls.sh -x sock -p 10002 -h localhost
        # check that they're running
        SAMP_433_PID=$(pgrep -f samp-4.3.3.conf)
        AGG_433_PID=$(pgrep -f agg-4.3.3.conf)
        AGG_4_PID=$(pgrep -f agg-4.conf)
        echo "--- ldmsds ---"
        pgrep -a ldmsd
        echo "--------------"
        [[ -n "${SAMP_433_PID}" ]] || error "samp-4.3.3 is not running"
        [[ -n "${AGG_433_PID}" ]] || error "agg-4.3.3 is not running"
        [[ -n "${AGG_4_PID}" ]] || error "agg-4 is not running"
        # ldms_ls-4 to agg-4.3.3
        echo -n "ldms_ls agg-4.3.3 ... "
        D0=$( ./ldms_ls.sh -x sock -p 10001 )
        echo "result: ${D0}"
        # ldms_ls-4 to agg-4
        echo -n "ldms_ls agg-4 ... "
        D1=$( ./ldms_ls.sh -x sock -p 10002 )
        echo "result: ${D1}"
        [[ -n "${D0}" ]] || error "ldms_ls FAILED agg-4.3.3 is empty"
        [[ "${D0}" = "${D1}" ]] && echo "ldms_ls verified" || error "ERROR: dir(agg-4.3.3) != dir(agg-4)"
        # kill samp-4.3.3 so that the set disappeared from agg-4.3.3
        echo "Killing samp-4.3.3"
        kill ${SAMP_433_PID}
        sleep 2
        # ldms_ls to agg-4.3.3
        echo -n "ldms_ls ... "
        D0=$(./ldms_ls.sh -x sock -p 10001)
        [[ -z "${D0}" ]] && echo "dir(agg-4.3.3) is empty (good)" || error "ERROR: dir(agg-4.3.3) is not empty"
        # check aggregators
        echo -n "checking agg-4.3.3 ... "
        [[ -d "/proc/${AGG_433_PID}" ]] && echo "alive!" || error "agg-4.3.3 is dead"
        echo -n "checking agg-4 ... "
        [[ -d "/proc/${AGG_4_PID}" ]] && echo "aive!" || error "agg-4 is dead"
        # ldms_ls to agg-4
        echo -n "ldms_ls ... "
        D1=$(./ldms_ls.sh -x sock -p 10002)
        [[ -z "${D1}" ]] && echo "dir(agg-4) is empty (good)" || error "ERROR: dir(agg-4) is not empty"
        echo "DONE!"
