name: C/C++ CI

on:
  push:
    branches: [ master, CI ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure CFLAGS='-Wall -Werror'
    - name: make
      run: make
